export const actionTypes = {
    LOG_IN: 'LOG_IN',
    TOGGLE_REGISTERED: 'TOGGLE_REGISTERED',
    UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
    REQUEST_DATA: 'REQUEST_DATA',
    GET_USERS: 'GET_USERS',
    GET_SURVEYS: 'GET_SURVEYS'
};