export const actionTypes = {
    UPDATE_HISTORY: 'UPDATE_HISTORY',
    GENERATE_PAIRS: 'GENERATE_PAIRS',
    UPDATE_TEXT_AREA_HEIGHT: 'UPDATE_TEXT_AREA_HEIGHT',
    TOGGLE_CAN_GENERATE: 'TOGGLE_CAN_GENERATE'
};